theme: jekyll-theme-minimal
title: TLP-WHITE
subtitle: Version l33t
description: Walkthroughs, challenges, and examples of host compromises
logo: /host-intrusion-img.png
show_downloads: false
google_analytics: UA-174336987-1
url: https://www.hostintrusion.com
read_time: true
